language: node_js
node_js: stable

install:
  - npm install hexo

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "CarpCai"
  - git config user.email "563998753@qq.com"
  - git add .
  - git commit -a -m "Auto update docs by Travis CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - git push --force --quiet "https://${GH_TOKEN_CODING}@${GH_REF_CODING}" master:master
branches:
  only:
    - hexo
env:
 global:
    - GH_REF: github.com/blinkfox/blinkfox.github.io.git
    - GH_REF_CODING: git.dev.tencent.com:carpcai/carpcai.coding.me.git